# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         rpm-build-perl
version:      0.5
version_from: lib/B/PerlReq.pm
installdirs:  site
requires:
    B:                             0
    Safe:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
