--- #YAML:1.0
name:                rpm-build-perl
version:             0.6.8
abstract:            Calculate dependencies for Perl sources
license:             ~
author:              
    - Alexey Tourbin <at@altlinux.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    B:                             0
    Encode:                        0
    O:                             0
    Safe:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
