---
abstract: 'Calculate dependencies for Perl sources'
author:
  - 'Alexey Tourbin <at@altlinux.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: rpm-build-perl
no_index:
  directory:
    - t
    - inc
requires:
  B: 0
  Encode: 0
  O: 0
  Safe: 0
  Test::More: 0
version: 0.82
